// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjbi2moOsgOdoCvPEy6Yp5GXxFQ0ZjNcQ',
    appId: '1:863774657605:web:47012a15d4517c6431672c',
    messagingSenderId: '863774657605',
    projectId: 'bloodinneed999',
    authDomain: 'bloodinneed999.firebaseapp.com',
    databaseURL: 'https://bloodinneed999.firebaseio.com',
    storageBucket: 'bloodinneed999.appspot.com',
    measurementId: 'G-7NZFXT1M7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl4pb3Meu1rXkg_fqGmNtiDQHyvWsOMmk',
    appId: '1:863774657605:android:f12393ec3104172a31672c',
    messagingSenderId: '863774657605',
    projectId: 'bloodinneed999',
    databaseURL: 'https://bloodinneed999.firebaseio.com',
    storageBucket: 'bloodinneed999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0kK8RNrz9vS84poamsN3gTna3fyuUaFg',
    appId: '1:863774657605:ios:39c6f2e6d7b27d9931672c',
    messagingSenderId: '863774657605',
    projectId: 'bloodinneed999',
    databaseURL: 'https://bloodinneed999.firebaseio.com',
    storageBucket: 'bloodinneed999.appspot.com',
    androidClientId: '863774657605-9cv6g0il0n4nks7nvliad8opp0jl18e2.apps.googleusercontent.com',
    iosBundleId: 'root.bloodinneed.devs.bloodInNeed',
  );
}
